### ISSUE TITLE
Vaadin 7.6.1 + SpringBoot

### ISSUE THREAD

**Issue by francesc3000** [markoradinovic/suggestfield#7]
Hello,
I am using Vaadin version 7.6.1 + SpringBoot and I am not able to use this addon because I'm retrieving this message error in runtime:
Widgetset 'com.vaadin.DefaultWidgetSet' does not contain implementation for org.vaadin.suggestfield.SuggestField. Check its component connector's @Connect mapping, widgetsets GWT module description file and re-compile your widgetset. In case you have downloaded a vaadin add-on package, you might want to refer to .

I cannot recompile my widgetset because I'm using Spring Boot, or I think so. I can use another addons with no problem.

Thank you.
BR.

**Comment by markoradinovic** [comment]
Hi,
you need to recompile your application widgetset. I also use Spring Boot and I don't have any problems. In your Widgetset.gwt.xml file you need to add:

```
<inherits name="org.vaadin.suggestfield.WidgetSet" />
```

If you are using maven and Vaadin Maven plugin, you can compile widgetset with following command:

```
mvn clean vaadin:compile
```

**Comment by francesc3000** [comment]
Hi, 
Thank you for your quick response. I'm trying to run my project with custom WidgetSet but I am not able. This is out of your add-on run configuration but I will be glad if you could give me some feedback.
I create my WidgetSet.gwt.xml under my project main directory "com.vaadin.example" and I modify my UI class with annotation @Widgetset("com.vaadin.example.WidgetSet").
My WidgetSet code is this:



```
<!-- WS Compiler: manually edited -->

<!-- Inherit DefaultWidgetSet  -->
<inherits name="com.vaadin.DefaultWidgetSet" /> 
<inherits name="org.vaadin.suggestfield.WidgetSet" />

<source path="client"/>
<source path="shared"/>
```



But when I run my application pop up is displayed with this information:
Failed to load widgetset: ./VAADIN/widgetsets/com.vaadin.example.WidgetSet/com.example.vaadin.WidgetSet.nocache.js?1453149865854

Am I doing something wrong?

If you do not want to reply to this message I get it.
Very thanks.

**Comment by markoradinovic** [comment]
Since you are using Spring Boot, I think that you have problem with static files location. Here is my old sample of Vaadin Maven plugin configuration:

```
<plugin>
<groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.plugin.version}</version>
                <configuration>
                    <extraJvmArgs>-Xmx1g -Xss1024k</extraJvmArgs>

                    <!-- We are doing "inplace" gwt compilation but into subdir VAADIN/widgetsets -->
                    <webappDirectory>${basedir}/src/main/public/VAADIN/widgetsets
                    </webappDirectory>
                    <hostedWebapp>${basedir}/src/main/public/VAADIN/widgetsets
                    </hostedWebapp>
                    <noServer>true</noServer>
                    <!-- Remove draftCompile when project is ready -->
                    <draftCompile>true</draftCompile>
                    <persistentunitcachedir>${project.build.directory}/gwtdirt</persistentunitcachedir>
                    <compileReport>true</compileReport>
                    <style>OBF</style>
                    <strict>true</strict>
                    <!-- Symbol maps etc, not needed in vaadin app, just target them outside 
                        war -->
                    <deploy>${project.build.directory}/gwt-deploy</deploy>
                </configuration>
                <executions>
                    <execution>
                        <configuration>
                            <!-- if you don't specify any modules, the plugin will find them -->
                            <!-- <modules> <module>com.vaadin.demo.mobilemail.gwt.ColorPickerWidgetSet</module> 
                                </modules> -->
                        </configuration>
                        <goals>
                            <goal>clean</goal>
                            <goal>resources</goal>
                            <!-- These are non functional currently with spring boot directory -->
                            <!-- structure <goal>update-theme</goal> <goal>update-widgetset</goal> -->
                            <goal>compile-theme</goal>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Also, you don't need this in gwt.xml:

```
<source path="client"/>
<source path="shared"/>
```

You could also update you WidgetSet.gwt.xml using Vaadin Maven plugin: mvn vaadin:update-widgetset

**Comment by francesc3000** [comment]
Hello,
Your widget works fine under Spring + Vaadin 7.6.1. If someone have the same issue here I found the solution.
[https://vaadin.com/forum#!/thread/9587133](url)
Thanks.
